Update User #105
Healthy-Lifestyle-Assistant/backend pull request #112
Opened 2023-11-07 17:38 UTC by Anastasiia2023

2023-11-08 12:55 UTC, TildaEndeavour approved these changes

2023-11-08 13:26 UTC, OlegKDev requested changes

2023-11-08 13:26 UTC, OlegKDev commented on src/test/java/healthy/lifestyle/backend/users/controller/UserControllerTest.java
> +
// When

2023-11-08 13:26 UTC, OlegKDev commented on src/test/java/healthy/lifestyle/backend/users/controller/UserControllerTest.java
> +                .andExpect(status().isOk())
User id also `.andExpect(jsonPath("$.id", ...`

2023-11-08 13:26 UTC, OlegKDev commented on src/test/java/healthy/lifestyle/backend/users/controller/UserControllerTest.java
> +
// When

2023-11-08 13:26 UTC, OlegKDev commented on src/test/java/healthy/lifestyle/backend/users/service/UserServiceTest.java
> +        when(userRepository.save(existingUser)).thenReturn(existingUser);
when(...) relates to the initial setup of a test, so it's something given before the test. In When section there is a method under a test, so "When" in a given-when-then relates to the main test event.

2023-11-09 14:00 UTC, OlegKDev approved these changes

2023-11-09 14:04 UTC, merged