Get User Details #121
Healthy-Lifestyle-Assistant/backend pull request #132
Opened 2023-11-13 18:41 UTC by Anastasiia2023

2023-11-14 08:49 UTC, OlegKDev requested changes

2023-11-14 08:49 UTC, OlegKDev commented on src/test/java/healthy/lifestyle/backend/users/service/UserServiceTest.java
> +        // assertThat(user.getId()).isEqualTo(actualDto.getId());
Remove commented line if it is not needed

2023-11-14 08:49 UTC, OlegKDev commented on src/test/java/healthy/lifestyle/backend/users/controller/UserControllerTest.java
> +                .andExpect(jsonPath("$.message", is(ErrorMessage.USER_RESOURCE_MISMATCH.getName())))
There is no such exception in the service method:

![image](https://github.com/Healthy-Lifestyle-Assistant/backend/assets/93421769/3ab70459-ef73-4358-a77d-6dfd391529d0)

2023-11-14 11:28 UTC, TildaEndeavour approved these changes

2023-11-15 09:22 UTC, OlegKDev approved these changes

2023-11-15 09:22 UTC, merged