Feature/154 get exercises admin
Healthy-Lifestyle-Assistant/backend pull request #163
Opened 2023-12-12 10:36 UTC by TildaEndeavour

2023-12-12 11:14 UTC, Anastasiia2023 approved these changes

2023-12-12 14:15 UTC, OlegKDev requested changes

2023-12-12 14:15 UTC, OlegKDev commented on src/main/java/healthy/lifestyle/backend/admin/exercises/controller/ExerciseAdminController.java
> +            @RequestParam(name = "needsEquipment", required = false) boolean needsEquipment) {
Please don't forget to use validation annotations for request parameters.

2024-01-03 10:12 UTC, OlegKucherenkoDev requested changes

2024-01-05 11:12 UTC, OlegKucherenkoDev requested changes

2024-01-05 11:12 UTC, OlegKucherenkoDev commented on src/test/java/healthy/lifestyle/backend/admin/workout/service/ExerciseAdminServiceTest.java
> +        Assertions.assertEquals(expectedExercises.size(), result.size());
`Assertions.assertEquals(resultSeeds.size(), result.size());` serves the same goal since resultSeeds gives us an expected output size.

2024-01-05 11:12 UTC, OlegKucherenkoDev commented on src/test/java/healthy/lifestyle/backend/admin/workout/service/ExerciseAdminServiceTest.java
> +        }
Actually we have expected seeds of the exercises, and we use them in lines 89-91. So I'm not sure if we need to duplicate the filter logic in the test in a separate class method.

2024-01-05 11:12 UTC, OlegKucherenkoDev commented on src/test/java/healthy/lifestyle/backend/admin/workout/service/ExerciseAdminServiceTest.java
> +                Arguments.of("NonExistentVale", "NonExistentVale", false, null, Collections.emptyList()),
Value?

2024-01-08 08:12 UTC, OlegKucherenkoDev approved these changes

2024-01-08 08:13 UTC, merged