Feature/179 Get default nutrition by id (Repository, Service, Controller)
Healthy-Lifestyle-Assistant/backend pull request #182
Opened 2024-01-17 16:44 UTC by TildaEndeavour

2024-01-17 19:05 UTC, Anastasiia2023 approved these changes

2024-01-18 11:00 UTC, OlegKucherenkoDev requested changes

2024-01-18 11:00 UTC, OlegKucherenkoDev commented on src/main/resources/changelog/migration.xml
> +                <constraints nullable="false" unique="false"/>
`name` field has `unique=true`

2024-01-18 11:00 UTC, OlegKucherenkoDev commented on src/main/resources/changelog/migration.xml
> +            </column>
`supplement` and `recipe` fields are redundant.

2024-01-18 11:00 UTC, OlegKucherenkoDev commented on src/main/resources/changelog/migration.xml
> +            </column>
`description` field has `nullable=true`

2024-01-18 11:00 UTC, OlegKucherenkoDev commented on src/main/resources/changelog/sql/default_nutritions.sql
> +INSERT INTO nutrition_types(id, name, supplement, recipe) VALUES
```sql
INSERT INTO nutrition_types(id, name) VALUES (1, 'Recipe'), (2, 'Supplement');
```

2024-01-18 11:00 UTC, OlegKucherenkoDev commented on src/main/resources/changelog/sql/default_nutritions.sql
> +(10, 'High-Protein Egg Breakfast', 'A satisfying breakfast featuring scrambled eggs, spinach, tomatoes, and whole grain toast.', false, 10);
These all are Recipes, so `nutrition_type_id` will be 1.
Examples of Supplements are: Multivitamins and Minerals, Omega, Protein, Q10, Lecithin, Collagen. They will have `nutrition_type_id` equaled to 2:

```sql
(11, 'Multivitamins and Minerals', 'Elevate your overall health with essential vitamins and minerals for a well-rounded nutritional foundation.', false, 2),
(12, 'Protein Shake', 'Fuel your body with the daily protein it needs for muscle repair, growth, and overall strength.', false, 2),
(13, 'Q10', 'Revitalize your energy levels and fortify your immune system with Q10, a powerful antioxidant supporting cellular energy production.', false, 2),
(14, 'Omega', 'Nourish your body with essential fatty acids for heart health, cognitive function, and overall well-being.', false, 2),
(15, 'Lecithin', 'Unlock the benefits of choline, an essential nutrient found in lecithin, supporting brain function and overall cognitive well-being.', false, 2),
(16, 'Collagen', 'Nurture your skin, hair, nails, and bones with collagen, promoting elasticity, strength, and structural integrity for a vibrant appearance and overall well-being.', false, 2);

ALTER sequence nutritions_id_seq restart with 17;
```

2024-01-18 15:06 UTC, OlegKucherenkoDev requested changes

2024-01-23 10:55 UTC, OlegKucherenkoDev approved these changes

2024-01-25 09:01 UTC, merged