Get Custom Mental With Filter And Pagination (Service+Controller) #186
Healthy-Lifestyle-Assistant/backend pull request #186
Opened 2024-01-31 11:48 UTC by Anastasiia2023

2024-01-31 14:30 UTC, OlegKucherenkoDev requested changes

2024-01-31 14:30 UTC, OlegKucherenkoDev commented on src/main/java/healthy/lifestyle/backend/mentals/controller/MentalController.java
> +    }
Seems okay, but I don't know why do you need `getCustomMentals()` if you have pre-authorized `getMentalsWithFilter()`.

2024-01-31 14:30 UTC, OlegKucherenkoDev commented on src/main/java/healthy/lifestyle/backend/mentals/repository/MentalJdbcRepository.java
> +public class MentalJdbcRepository {
Why do you need all that Jdbc? I've found a better solution. If you copy-past code, I suggest you to pay attention is it a part of the production or at least testing release.

2024-01-31 16:07 UTC, TildaEndeavour approved these changes

2024-02-07 07:04 UTC, OlegKucherenkoDev approved these changes

2024-02-21 12:10 UTC, OlegKucherenkoDev approved these changes

2024-02-28 11:29 UTC, closed without merging