Delete Custom Mental(Repository, Service, Controller)
Healthy-Lifestyle-Assistant/backend pull request #202
Opened 2024-05-14 10:09 UTC by Anastasiia2023

2024-05-15 06:50 UTC, OlegKucherenkoDev requested changes

2024-05-15 06:50 UTC, OlegKucherenkoDev commented on src/main/java/healthy/lifestyle/backend/user/service/UserServiceImpl.java
> +        if (user.getMentals() != null) user.getMentals().remove(mental);
How do you think, should we check whether this particular user has this particular mental entity? (user-mental mismatch)

2024-05-16 17:56 UTC, OlegKucherenkoDev approved these changes

2024-05-17 13:31 UTC, TildaEndeavour approved these changes

2024-05-18 06:56 UTC, merged