Setup Workout Plan
Healthy-Lifestyle-Assistant/backend pull request #207
Opened 2024-05-22 13:45 UTC by TildaEndeavour

2024-05-22 14:53 UTC, OlegKucherenkoDev requested changes

2024-05-22 14:53 UTC, OlegKucherenkoDev commented on src/main/java/healthy/lifestyle/backend/plan/workout/service/WorkoutPlanServiceImpl.java
> +                });
Если присутствует и активный

2024-05-22 14:53 UTC, OlegKucherenkoDev commented on src/main/java/healthy/lifestyle/backend/plan/workout/service/WorkoutPlanServiceImpl.java
> +        // Only one workout-plan association is allowed
// Only one active workout-plan association is allowed

2024-05-22 14:53 UTC, OlegKucherenkoDev commented on src/main/java/healthy/lifestyle/backend/plan/workout/model/WorkoutPlan.java
> +    private JsonNode jsonDescription;
```java
private List<JsonDescription> jsonDescription;
```

```java
public class JsonDescription {
    private long json_id;
    private DayOfWeek dayOfWeek;
    private int hours;
    private int minutes;
}

```

2024-05-23 12:12 UTC, Anastasiia2023 approved these changes

2024-05-29 18:38 UTC, OlegKucherenkoDev commented on src/main/java/healthy/lifestyle/backend/plan/workout/service/WorkoutPlanServiceImpl.java
> +        if (requestDto.getStartDate() == null || requestDto.getEndDate() == null) {
hello

2024-05-30 06:07 UTC, OlegKucherenkoDev commented on src/test/java/healthy/lifestyle/backend/plan/workout/service/WorkoutPlanServiceImplTest.java
> +    TestUtil dataUtil = new TestUtil();
```java
@Spy
TestUtil testUtil;
```
в одном стиле

2024-05-30 06:07 UTC, OlegKucherenkoDev commented on src/test/java/healthy/lifestyle/backend/plan/workout/service/WorkoutPlanServiceImplTest.java
> +
отсупы в одном стиле

2024-05-30 06:08 UTC, OlegKucherenkoDev commented on src/test/java/healthy/lifestyle/backend/plan/workout/service/WorkoutPlanServiceImplTest.java
> +
отсупы в одном стиле

2024-05-30 06:08 UTC, OlegKucherenkoDev commented on src/test/java/healthy/lifestyle/backend/plan/workout/service/WorkoutPlanServiceImplTest.java
> +
отсупы в одном стиле

2024-05-30 06:08 UTC, OlegKucherenkoDev commented on src/test/java/healthy/lifestyle/backend/plan/workout/service/WorkoutPlanServiceImplTest.java
> +
given/when/then

2024-06-14 15:33 UTC, OlehKDev approved these changes

2024-06-14 15:34 UTC, merged