Get default mental workout by
Healthy-Lifestyle-Assistant/backend pull request #214
Opened 2024-06-17 12:56 UTC by Anastasiia2023

2024-06-18 13:24 UTC, OlegKDev requested changes

2024-06-18 13:24 UTC, OlehKDev commented on src/main/java/healthy/lifestyle/backend/security/SecurityConfig.java
> +                        .permitAll()
Probably, place it near other mental activities

2024-06-18 13:24 UTC, OlehKDev commented on src/test/java/healthy/lifestyle/backend/activity/mental/controller/MentalWorkoutControllerTest.java
> +                .isEqualTo(defaultMentalWorkout);
Consider checking whether there are two mental activities in the response 
`assertEquals(defaultMentalWorkout.getMentalActivites.size(), responseDto.getMentalActivites.size())`

2024-06-18 16:20 UTC, TildaEndeavour approved these changes

2024-06-26 09:42 UTC, OlehKDev approved these changes

2024-06-26 09:42 UTC, merged