Get List Default MentalWorkout
Healthy-Lifestyle-Assistant/backend pull request #216
Opened 2024-06-18 11:54 UTC by Anastasiia2023

2024-06-18 13:33 UTC, OlehKDev requested changes

2024-06-18 13:33 UTC, OlehKDev commented on src/main/java/healthy/lifestyle/backend/activity/mental/controller/MentalWorkoutController.java
> +    public ResponseEntity<Page<MentalWorkoutResponseDto>> getAllMentalWorkouts(
Probaly, `getDefaultMentalWorkout`?

2024-06-18 13:33 UTC, OlehKDev commented on src/main/java/healthy/lifestyle/backend/activity/mental/controller/MentalWorkoutController.java
> +            @RequestParam(required = false, defaultValue = "0") int pageNumber) {
What about filtering by title, description, mental type?

2024-07-02 15:31 UTC, OlegKDev approved these changes

2024-07-02 15:31 UTC, merged